-- First slide deck: "How to be an AI engineer in today's world?"
-- 11 slides at roughly 1-1.5 minutes each, so the full deck presents in ~15 minutes.
-- Idempotent: re-running replaces this deck's slides with the content below.
INSERT INTO slide_decks (slug, title, description, status, sort_order)
VALUES (
  'how-to-be-an-ai-engineer',
  'How to be an AI engineer in today''s world?',
  'Subjects to study, skills to build, what employers look for, and salary ranges internationally and in the Philippines. 11 slides, about 15 minutes.',
  'published',
  0
)
ON CONFLICT (slug) DO NOTHING;

DELETE FROM slides WHERE deck_id = (SELECT id FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer');

-- Slide 1: cover
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'How to be an AI engineer in today''s world?', $slide${"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Subjects · skills · hiring signals · salaries"}]},{"type":"paragraph","content":[{"type":"text","text":"A practical map for becoming an AI engineer — what to study, what to build, and what the market pays."}]},{"type":"paragraph","content":[{"type":"text","text":"11 slides · about 15 minutes"}]}]}$slide$::jsonb, 'Welcome the audience and set the promise: by the end they will have a concrete study list, a skill checklist, and realistic salary numbers.', 0
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 2: what the role is
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What an AI engineer actually does', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Builds products on top of foundation models "},{"type":"text","text":"— chat, search, agents, automation — instead of training models from scratch."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Sits between software engineering and ML: "},{"type":"text","text":"APIs, data pipelines, retrieval, evaluation, and product glue."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Not an ML researcher "},{"type":"text","text":"(novel architectures, papers) and not a classic data scientist (dashboards, analysis) — though the lines blur."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"The core loop: "},{"type":"text","text":"prototype with an LLM API, ground it with your data (RAG), evaluate, ship, measure."}]}]}]}]}$slide$::jsonb, 'Draw the boundary clearly: AI engineers ship products powered by models. Researchers advance models. The confusion between the two derails a lot of study plans.', 1
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 3: subjects, engineering foundations
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Subjects I — engineering foundations', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Programming: "},{"type":"text","text":"Python first, plus one production language (TypeScript, Go, or Java)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Data structures and algorithms "},{"type":"text","text":"— enough to pass interviews and write sane code."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Databases and SQL: "},{"type":"text","text":"Postgres fundamentals, indexing, and how vector search differs."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"APIs and HTTP: "},{"type":"text","text":"REST, JSON, auth, webhooks — AI features ship as API calls."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Git, Linux, Docker: "},{"type":"text","text":"the unglamorous skills every employer assumes you have."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Basic statistics: "},{"type":"text","text":"distributions, sampling, and what accuracy numbers actually hide."}]}]}]}]}$slide$::jsonb, 'Stress that AI engineering is still engineering. Candidates who skip foundations hit a ceiling fast, no matter how good their prompts are.', 2
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 4: subjects, AI core
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Subjects II — AI core', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Machine-learning fundamentals: "},{"type":"text","text":"training vs inference, overfitting, train/test splits."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Deep-learning basics: "},{"type":"text","text":"neural nets, embeddings, and what a transformer does at a high level."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"NLP essentials: "},{"type":"text","text":"tokens, context windows, and attention as intuition, not proofs."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Just enough math: "},{"type":"text","text":"vectors, similarity search, and cosine distance for retrieval."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Skip the PhD track: "},{"type":"text","text":"you need working intuition, not derivations — most AI engineers never train a foundation model."}]}]}]}]}$slide$::jsonb, 'Reassure the audience: no advanced math degree required. Intuition plus hands-on practice beats theory without shipping.', 3
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 5: skills, AI toolkit
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Skills I — the AI toolkit', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Prompt engineering: "},{"type":"text","text":"instructions, examples, constraints, and strict output formats."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Context engineering: "},{"type":"text","text":"getting the right knowledge into the window — chunking, retrieval, memory."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"RAG pipelines: "},{"type":"text","text":"ingest, embed, retrieve, generate, cite — and knowing where each step breaks."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Function calling and agents: "},{"type":"text","text":"tools, planning loops, guardrails, human-in-the-loop."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Evaluation: "},{"type":"text","text":"golden test sets, LLM-as-judge, and regression tests for prompts."}]}]}]}]}$slide$::jsonb, 'Evaluation is the differentiator. Anyone can call an API; professionals can prove their system works and catch regressions.', 4
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 6: skills, shipping
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Skills II — shipping it', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Full-stack glue: "},{"type":"text","text":"a web framework (Next.js, Django, Laravel) to wrap models in real products."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Vector databases: "},{"type":"text","text":"pgvector, Pinecone, or Qdrant — plus knowing when plain full-text search is enough."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Cloud and DevOps basics: "},{"type":"text","text":"deploy containers, manage secrets, control GPU and API costs."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Observability: "},{"type":"text","text":"log prompts, trace agent runs, track token spend per feature."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Security and privacy: "},{"type":"text","text":"PII redaction, prompt-injection awareness, data-retention policies."}]}]}]}]}$slide$::jsonb, 'Demos are easy, production is the job. Cost control and observability are what separate prototypes from products.', 5
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 7: employers, what they want
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What employers look for I', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Shipped AI features, not certificates: "},{"type":"text","text":"a live demo beats ten course completions."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"An evals mindset: "},{"type":"text","text":"“how do you know it works?” is the new senior-level interview question."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Product sense: "},{"type":"text","text":"knowing which problems deserve AI — and which deserve a regex."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Communication: "},{"type":"text","text":"explaining cost, latency, and accuracy trade-offs to non-technical stakeholders."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Adaptability: "},{"type":"text","text":"the stack changes monthly — show you learn in public through writing, repos, and talks."}]}]}]}]}$slide$::jsonb, 'Hammer the portfolio point: hiring managers skim certificates and click demos. One live project outweighs a wall of badges.', 6
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 8: employers, standing out
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What employers look for II — stand out', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Build in public: "},{"type":"text","text":"side projects with real users, even tiny ones."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Write and teach: "},{"type":"text","text":"blog posts explaining what you built signal senior-level thinking."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Contribute upstream: "},{"type":"text","text":"docs, bug fixes, and evals for open-source AI projects all count."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Bring a domain: "},{"type":"text","text":"finance, healthcare, support ops — AI plus expertise is rare and paid well."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Red flags managers mention: "},{"type":"text","text":"tutorial-only knowledge, no shipped work, “I used ChatGPT” as the whole story."}]}]}]}]}$slide$::jsonb, 'End on the domain point: the highest-paid AI engineers are rarely the best at models — they are the best at models applied to something valuable.', 7
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 9: salaries, international
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Salary ranges — international', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Approximate annual total compensation, 2025–2026. Ranges move fast — treat these as orientation, not offers."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"United States: "},{"type":"text","text":"junior $120k–$160k · mid $160k–$220k · senior $220k–$300k+."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Staff and principal at top labs and Big Tech: "},{"type":"text","text":"$300k–$600k+ with equity."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Western Europe: "},{"type":"text","text":"typically €60k–€120k; senior roles in London, Berlin, and Amsterdam run higher."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Remote for US/EU companies: "},{"type":"text","text":"commonly $80k–$180k depending on seniority and timezone overlap."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"The pattern: "},{"type":"text","text":"AI premiums are real but concentrated in people who ship and evaluate."}]}]}]}]}$slide$::jsonb, 'Caveat the numbers out loud: levels and equity vary wildly. The junior US band surprises people — pair it with cost-of-living context if asked.', 8
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 10: salaries, Philippines
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Salary ranges — Philippines', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Approximate monthly ranges, 2025–2026. Foreign-remote work is the single biggest lever for PH-based engineers."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Local product companies: "},{"type":"text","text":"junior ₱30k–₱60k · mid ₱60k–₱120k · senior ₱120k–₱200k+ per month."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Remote for foreign clients: "},{"type":"text","text":"roughly $2k–$8k+/mo (₱115k–₱460k+) depending on seniority and proof of work."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"BPO and shared-services AI roles: "},{"type":"text","text":"steadier, usually 20–40% below product-company pay."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Freelance and consulting: "},{"type":"text","text":"₱50k–₱300k+ per engagement once you have demonstrable results."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"What moves you up fastest: "},{"type":"text","text":"a shipped portfolio, strong English communication, and overlap with client hours."}]}]}]}]}$slide$::jsonb, 'This slide usually gets the most questions. Emphasize the portfolio-to-remote pipeline: local experience plus public proof unlocks foreign rates.', 9
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 11: roadmap and close
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Your 90-day roadmap', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Days 1–30: "},{"type":"text","text":"Python plus APIs plus one LLM API. Ship a tiny chatbot. Learn prompting by doing."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Days 31–60: "},{"type":"text","text":"build a RAG app over real documents. Add evals. Deploy it with Docker."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Days 61–90: "},{"type":"text","text":"ship a second project with agents or tools. Write about both. Start applying."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Every week: "},{"type":"text","text":"one public artifact — a commit, a post, a demo video. Visibility compounds."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Closing thought: "},{"type":"text","text":"the title “AI engineer” is earned by shipped work. Start small, ship weekly, and the rest follows."}]}]}]}]}$slide$::jsonb, 'Close with the call to action: pick the day-1 chatbot this week. Offer to take questions on salaries and roadmaps first — that is what audiences remember.', 10
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';
