-- Retarget the AI engineer deck at a non-technical audience (college professors with
-- little to no AI background): plain language, spelled-out terms, academic-friendly
-- analogies. Same 11 slides, same ~15 minute length.
-- Idempotent: re-running replaces this deck's slides with the content below.
UPDATE slide_decks
SET description = 'A plain-language guide: what to study, which skills matter, what employers want, and what it pays — internationally and in the Philippines. 11 slides, about 15 minutes.'
WHERE slug = 'how-to-be-an-ai-engineer';

DELETE FROM slides WHERE deck_id = (SELECT id FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer');

-- Slide 1: cover
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'How to be an AI engineer in today''s world?', $slide${"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"What to study · which skills matter · what employers want · what it pays"}]},{"type":"paragraph","content":[{"type":"text","text":"A plain-language map for anyone curious about the AI engineering career — no technical background assumed."}]},{"type":"paragraph","content":[{"type":"text","text":"11 slides · about 15 minutes"}]}]}$slide$::jsonb, 'Welcome a non-technical audience. Promise no jargon without explanation, and invite questions at any point rather than saving them.', 0
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 2: what the role is
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What an AI engineer actually does', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Builds practical tools on top of AI systems like ChatGPT "},{"type":"text","text":"— for example, a chatbot that answers questions from your own documents."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Think of it this way: "},{"type":"text","text":"the AI company builds the engine; the AI engineer builds the car around it."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Different from an AI researcher "},{"type":"text","text":"(who invents new AI methods) and from a data analyst (who studies numbers in spreadsheets)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"The daily work: "},{"type":"text","text":"connect AI to real information, check that its answers are correct, and put it in front of users."}]}]}]}]}$slide$::jsonb, 'The engine-vs-car analogy usually lands. Pause here and confirm the researcher-vs-engineer distinction is clear before moving on.', 1
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 3: subjects, computer foundations
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Subjects I — computer foundations', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Programming: "},{"type":"text","text":"writing step-by-step instructions a computer follows. Python is the friendliest first language."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"How computers store and find information: "},{"type":"text","text":"databases, and the question language called SQL."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"How programs talk to each other online: "},{"type":"text","text":"AI features are delivered as internet requests between services."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Everyday technical habits: "},{"type":"text","text":"organizing files and code, and using modern tools — increasingly with AI assistance."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Basic statistics: "},{"type":"text","text":"averages, samples, and what a “90% accurate” claim really means."}]}]}]}]}$slide$::jsonb, 'Reassure the room: these are ordinary computer literacy topics, not genius-level math. Most can be learned online for free.', 2
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 4: subjects, AI essentials
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Subjects II — AI essentials', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"How AI learns from examples: "},{"type":"text","text":"the basic idea behind training, in plain terms."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"How AI compares meanings: "},{"type":"text","text":"words become numbers, so similarity becomes measurable."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"How chatbots write answers: "},{"type":"text","text":"prediction one word at a time, limited by short-term memory."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Connecting AI to your own documents "},{"type":"text","text":"so it answers from your material instead of guessing."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"No advanced mathematics required: "},{"type":"text","text":"working understanding beats equations for this career."}]}]}]}]}$slide$::jsonb, 'The no-advanced-math point is the one professors will repeat to students, so say it twice and give an example of a successful engineer without a math degree.', 3
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 5: skills, working with AI
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Skills I — working with AI', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Giving clear instructions: "},{"type":"text","text":"the clearer the request, the better the answer."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Providing background first: "},{"type":"text","text":"like handing a research assistant the readings before asking questions."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Linking AI to documents: "},{"type":"text","text":"the technique that lets a chatbot quote your syllabus or handbook."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Checking the work: "},{"type":"text","text":"small automatic tests so wrong answers are caught before users see them."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Setting limits: "},{"type":"text","text":"deciding when AI may act alone and when a person must approve."}]}]}]}]}$slide$::jsonb, 'The research-assistant analogy connects directly to academic life. Offer a live example: ask a chatbot a question with and without background material.', 4
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 6: skills, building real products
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Skills II — building real products', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Putting AI inside websites and apps "},{"type":"text","text":"that people actually use every day."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Storing knowledge for fast searching, "},{"type":"text","text":"including free tools anyone can start with."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Publishing projects online safely: "},{"type":"text","text":"passwords, private data, and access control done right."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Watching costs: "},{"type":"text","text":"AI services charge per use, so professionals track spending per feature."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Protecting privacy: "},{"type":"text","text":"removing personal details before data ever reaches an AI service."}]}]}]}]}$slide$::jsonb, 'Cost and privacy are the two points administrators care about most. Mention that a careless setup can leak student data or run up bills.', 5
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 7: employers, what they want
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What employers look for I', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Finished projects they can click and try: "},{"type":"text","text":"one working demo beats ten certificates."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Proof of checking answers "},{"type":"text","text":"instead of trusting AI output blindly."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Good judgment: "},{"type":"text","text":"knowing when AI is the right tool — and when a simple solution is better."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Clear communication: "},{"type":"text","text":"explaining cost, speed, and accuracy trade-offs to non-technical colleagues."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Curiosity and steady learning: "},{"type":"text","text":"this field changes every few months."}]}]}]}]}$slide$::jsonb, 'Compare certificates to diplomas and demos to published papers: hiring managers skim the former and read the latter.', 6
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 8: employers, standing out
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What employers look for II — stand out', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Build small projects in public, "},{"type":"text","text":"even simple ones with only a handful of users."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Write about what you build: "},{"type":"text","text":"explaining clearly signals senior-level thinking."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Help improve free AI tools: "},{"type":"text","text":"documentation and small fixes all count as experience."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Combine AI with a field you know: "},{"type":"text","text":"education, healthcare, law — that mix is rare and well paid."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Warning signs employers mention: "},{"type":"text","text":"only following tutorials, nothing finished, “I tried ChatGPT once” as the whole story."}]}]}]}]}$slide$::jsonb, 'Point at the room: professors already own the hardest half of the equation — deep domain knowledge. AI skills on top of that are extremely valuable.', 7
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 9: salaries, international
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Salary ranges — international', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Approximate yearly pay, 2025–2026. Treat these as orientation, not promises — levels and benefits vary widely."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"United States beginners: "},{"type":"text","text":"around $120,000–$160,000 per year; experienced: $160,000–$220,000; senior experts: $220,000–$300,000 or more."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Top experts at famous AI labs: "},{"type":"text","text":"$300,000–$600,000+ per year including company shares."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Western Europe: "},{"type":"text","text":"typically €60,000–€120,000 per year; London and Berlin pay more at senior levels."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Remote work for American or European companies: "},{"type":"text","text":"commonly $80,000–$180,000 per year."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"The pattern: "},{"type":"text","text":"the highest pay goes to people who finish projects and verify their AI's work."}]}]}]}]}$slide$::jsonb, 'Read one number slowly and let it land — for example, what a senior expert earns. Then caveat cost of living before questions start.', 8
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 10: salaries, Philippines
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Salary ranges — Philippines', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Approximate monthly pay, 2025–2026. Remote work for foreign clients pays the most by far."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Local tech companies: "},{"type":"text","text":"beginners ₱30k–₱60k · experienced ₱60k–₱120k · senior ₱120k–₱200k+ per month."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Remote work for foreign clients: "},{"type":"text","text":"roughly $2,000–$8,000+ per month (₱115,000–₱460,000+)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Back-office AI support roles: "},{"type":"text","text":"steadier, usually 20–40% below tech-company pay."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Independent consulting: "},{"type":"text","text":"₱50,000–₱300,000+ per project once you can show results."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Fastest way up: "},{"type":"text","text":"finished work to show, strong English, and hours that overlap with clients."}]}]}]}]}$slide$::jsonb, 'Expect the most questions here. Emphasize the path: local experience plus public proof of work unlocks foreign remote rates.', 9
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 11: roadmap and close
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Your 90-day roadmap', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Days 1–30: "},{"type":"text","text":"learn Python basics and try one AI service. Build a tiny chatbot that answers questions. Learn by doing."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Days 31–60: "},{"type":"text","text":"build a chatbot that answers from your own files. Add simple answer checks. Publish it online."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Days 61–90: "},{"type":"text","text":"build a second project that takes actions, like looking things up or drafting emails. Write about both. Start applying."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Every week: "},{"type":"text","text":"produce one visible result — finished code, a short article, a demo video. Small steps compound."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"Closing thought: "},{"type":"text","text":"the title “AI engineer” is earned through finished work. Start small, finish weekly, and the rest follows."}]}]}]}]}$slide$::jsonb, 'Close with one concrete assignment: build the day-1 chatbot this week. Offer to take questions on salaries and study paths first.', 10
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';
