-- Retarget the AI engineer deck at its real audience: college professors with little or
-- no AI background, with the goal of motivating them to use AI in their profession or a
-- side hustle. Replaces the career-switcher framing (roles, employer checklists, two salary
-- slides, job-application roadmap) with faculty use cases, fears, domain-expertise
-- advantage, side-hustle paths, and a professor-edition roadmap. 12 slides, ~15 minutes.
-- Idempotent: re-running replaces this deck's slides with the content below.
UPDATE slide_decks
SET title = 'AI for professors: use it, teach with it, earn from it',
    description = 'A plain-language talk for educators with little or no AI background: what AI can do for you this week, how it works, why your expertise is the rare skill, side-hustle paths, what it pays, and a 90-day roadmap. 12 slides, about 15 minutes.'
WHERE slug = 'how-to-be-an-ai-engineer';

DELETE FROM slides WHERE deck_id = (SELECT id FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer');

-- Slide 1: AI for professors: use it, teach with it, earn from it
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'AI for professors: use it, teach with it, earn from it', $slide${"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"What AI can do for you · How it works · Where your expertise fits · What it pays"}]},{"type":"paragraph","content":[{"type":"text","text":"A plain-language talk for educators with little or no AI background. No programming needed to start."}]},{"type":"paragraph","content":[{"type":"text","text":"12 slides · about 15 minutes"}]}]}$slide$::jsonb, 'Welcome a non-technical audience. Promise no jargon without explanation, and invite questions at any point rather than saving them. Frame the goal early: by the end, each person should have one thing to try this week.', 0
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 2: What AI can do for you this week
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What AI can do for you this week', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Concrete uses that need nothing but a free chatbot account and your own material."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Prepare lectures faster: ","marks":[{"type":"bold"}]},{"type":"text","text":"turn a chapter or paper into an outline, quiz questions, or three explanations at different levels."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Answer student questions at scale: ","marks":[{"type":"bold"}]},{"type":"text","text":"a chatbot loaded with your syllabus and handouts replies to the same question the hundredth time."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Read research faster: ","marks":[{"type":"bold"}]},{"type":"text","text":"summarize a stack of papers, then ask follow-up questions as if the author were in the room."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Give feedback at scale: ","marks":[{"type":"bold"}]},{"type":"text","text":"a first-pass rubric check on drafts, so your time goes to the judgment calls."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Draft the boring parts: ","marks":[{"type":"bold"}]},{"type":"text","text":"emails, rubrics, course descriptions, grant boilerplate. You edit; it types."}]}]}]}]}$slide$::jsonb, 'Pick the one example closest to this room''s discipline and spend most of the minute on it. Ask who has already tried a chatbot for teaching; build on their answer.', 1
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 3: What an AI engineer actually does
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What an AI engineer actually does', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Builds practical tools on top of AI systems like ChatGPT, ","marks":[{"type":"bold"}]},{"type":"text","text":"for example a chatbot that answers questions from your own documents."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Think of it this way: ","marks":[{"type":"bold"}]},{"type":"text","text":"the AI company builds the engine; the AI engineer builds the car around it."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Different from an AI researcher ","marks":[{"type":"bold"}]},{"type":"text","text":"(who invents new AI methods) and from a data analyst (who studies numbers in spreadsheets)."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"The daily work: ","marks":[{"type":"bold"}]},{"type":"text","text":"connect AI to real information, check that its answers are correct, and put it in front of users."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Why it matters to you: ","marks":[{"type":"bold"}]},{"type":"text","text":"the same skills, at a smaller scale, let a professor build tools for one course or one client."}]}]}]}]}$slide$::jsonb, 'The engine-vs-car analogy usually lands. Pause and confirm the researcher-vs-engineer distinction is clear. Stress that this talk is about the reachable version of the role, not the doctorate path.', 2
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 4: Common fears, honest answers
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Common fears, honest answers', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"“It makes things up.” ","marks":[{"type":"bold"}]},{"type":"text","text":"True. It predicts likely words, not facts. The fix is giving it your documents and checking its answers, which is exactly the skill this talk teaches."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"“Students will cheat.” ","marks":[{"type":"bold"}]},{"type":"text","text":"Some will, as with calculators and Wikipedia. Assignments that ask for reasoning, sources, and revision hold up better than ones that ask for recall."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"“It will replace teachers.” ","marks":[{"type":"bold"}]},{"type":"text","text":"It replaces tasks, not judgment. The people at risk are those who refuse to use it, not those who use it well."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"“I am too late or too old for this.” ","marks":[{"type":"bold"}]},{"type":"text","text":"Most working AI engineers learned these tools in the last three years. The field is new for everyone."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"“It is expensive.” ","marks":[{"type":"bold"}]},{"type":"text","text":"Free tiers cover experimentation. Paid use costs cents per question, and you can cap spending."}]}]}]}]}$slide$::jsonb, 'Invite the room to add a fear you missed. Answer briefly and move on; do not let this slide become the whole session. The point is trust, not debate.', 3
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 5: How AI works, in plain terms
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'How AI works, in plain terms', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"It learns from examples: ","marks":[{"type":"bold"}]},{"type":"text","text":"shown millions of texts, it picks up patterns in how words follow each other."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"It compares meanings as numbers: ","marks":[{"type":"bold"}]},{"type":"text","text":"words become coordinates, so “similar meaning” becomes a measurable distance."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"It writes one word at a time: ","marks":[{"type":"bold"}]},{"type":"text","text":"each word is a prediction based on the words before it, with a limited short-term memory."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"It can be pointed at your material: ","marks":[{"type":"bold"}]},{"type":"text","text":"give it your documents and it answers from them instead of guessing. This is the single most useful technique."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"No advanced mathematics required: ","marks":[{"type":"bold"}]},{"type":"text","text":"a working understanding beats equations for using and building with AI."}]}]}]}]}$slide$::jsonb, 'The no-advanced-math point is the one professors will repeat to students, so say it twice. Give an example of a successful AI engineer without a math degree.', 4
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 6: Skills anyone can learn
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Skills anyone can learn', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Give clear instructions: ","marks":[{"type":"bold"}]},{"type":"text","text":"the clearer the request, the better the answer. Specify audience, length, and format."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Provide background first: ","marks":[{"type":"bold"}]},{"type":"text","text":"like handing a research assistant the readings before asking questions."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Check the work: ","marks":[{"type":"bold"}]},{"type":"text","text":"ask for sources, spot-check facts, and test the same question two ways before trusting an answer."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Set limits: ","marks":[{"type":"bold"}]},{"type":"text","text":"decide when AI may act alone and when a person must approve. Grading and student records need a person."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Iterate: ","marks":[{"type":"bold"}]},{"type":"text","text":"the first answer is a draft. Ask for changes the way you would with a student."}]}]}]}]}$slide$::jsonb, 'The research-assistant analogy connects directly to academic life. Do a live example: ask a chatbot a question with and without background material.', 5
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 7: Your unfair advantage: domain expertise
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Your unfair advantage: domain expertise', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The rarest and best-paid AI skill is not programming. It is knowing a field deeply enough to judge when the AI is wrong."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"You already own the hard half: ","marks":[{"type":"bold"}]},{"type":"text","text":"years of subject knowledge, teaching judgment, and a sense of what good work looks like."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Engineers lack what you have: ","marks":[{"type":"bold"}]},{"type":"text","text":"a programmer can wire up a chatbot in a day but cannot tell whether its chemistry, law, or history is right."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Expert plus AI beats either alone: ","marks":[{"type":"bold"}]},{"type":"text","text":"employers and clients pay for people who combine a field with working AI skills."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Your students are your test group: ","marks":[{"type":"bold"}]},{"type":"text","text":"few people have a room of real users every semester."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Your network is your market: ","marks":[{"type":"bold"}]},{"type":"text","text":"colleagues, departments, schools, and alumni all have the same problems you do."}]}]}]}]}$slide$::jsonb, 'Point at the room. This is the emotional center of the talk: they are not starting from zero, they are starting from the harder-to-get half.', 6
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 8: Side-hustle paths for academics
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Side-hustle paths for academics', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Ways educators are already earning with AI, roughly in order of effort."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Sell your course materials: ","marks":[{"type":"bold"}]},{"type":"text","text":"AI-assisted study guides, question banks, and short courses on your subject, published on course platforms."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Consult for your own sector: ","marks":[{"type":"bold"}]},{"type":"text","text":"help schools, departments, or publishers adopt AI safely: policy, training, tool selection. Day rates, not hourly."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Build a subject-specific tutor: ","marks":[{"type":"bold"}]},{"type":"text","text":"a chatbot trained on your notes for one course, sold to students or licensed to another school."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Offer AI-assisted services: ","marks":[{"type":"bold"}]},{"type":"text","text":"editing, translation, research summaries, grant drafting, in fields where you can judge quality."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Teach the teachers: ","marks":[{"type":"bold"}]},{"type":"text","text":"workshops like this one. Demand is high and most trainers know less about your field than you do."}]}]}]}]}$slide$::jsonb, 'Ask which one the room would try. Note that the first two need no code at all, and the third needs less than a weekend with modern tools.', 7
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 9: Going deeper: technical foundations
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Going deeper: technical foundations', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Optional. Only needed if you want to build tools yourself rather than use them. Each is ordinary computer literacy, not advanced math."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Programming: ","marks":[{"type":"bold"}]},{"type":"text","text":"writing step-by-step instructions a computer follows. Python is the friendliest first language, and AI assistants now write most of it with you."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Storing and finding information: ","marks":[{"type":"bold"}]},{"type":"text","text":"databases, and the question language called SQL."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"How programs talk online: ","marks":[{"type":"bold"}]},{"type":"text","text":"AI features are delivered as internet requests between services."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Everyday technical habits: ","marks":[{"type":"bold"}]},{"type":"text","text":"organizing files and code, and using modern tools with AI assistance."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Basic statistics: ","marks":[{"type":"bold"}]},{"type":"text","text":"averages, samples, and what a “90% accurate” claim really means."}]}]}]}]}$slide$::jsonb, 'Reassure the room: this is the optional path, and everything here can be learned free online. AI coding assistants have lowered this bar sharply in the last two years.', 8
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 10: Building responsibly: cost, privacy, students
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Building responsibly: cost, privacy, students', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Protect student data: ","marks":[{"type":"bold"}]},{"type":"text","text":"never paste names, grades, or IDs into a public chatbot. Remove personal details first, or use a tool your school has approved."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Know what the tool does with your text: ","marks":[{"type":"bold"}]},{"type":"text","text":"free consumer tools may train on your input. Paid and education plans usually do not. Read the setting."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Watch costs: ","marks":[{"type":"bold"}]},{"type":"text","text":"AI services charge per use. Set a monthly cap before you build anything for a class."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Keep a person in the loop: ","marks":[{"type":"bold"}]},{"type":"text","text":"AI drafts, a human decides, especially for grades, admissions, and anything that affects a student's record."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Be transparent: ","marks":[{"type":"bold"}]},{"type":"text","text":"tell students when and how you use AI, and set the same expectation for them."}]}]}]}]}$slide$::jsonb, 'Cost and privacy are the two points administrators care about most. Mention that a careless setup can leak student data or run up bills, and that both are easy to prevent.', 9
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 11: What it pays
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'What it pays', $slide${"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Approximate figures, 2025–2026, from public salary guides. Orientation, not promises. Levels, benefits, and cost of living vary widely."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Full-time AI engineer, United States: ","marks":[{"type":"bold"}]},{"type":"text","text":"roughly $120,000–$220,000 per year; Western Europe €60,000–€120,000."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Full-time, Philippines local companies: ","marks":[{"type":"bold"}]},{"type":"text","text":"₱30k–₱60k per month starting, ₱120k–₱200k+ senior."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Remote work for foreign clients: ","marks":[{"type":"bold"}]},{"type":"text","text":"roughly $2,000–$8,000+ per month, the biggest jump available from the Philippines."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Consulting and training: ","marks":[{"type":"bold"}]},{"type":"text","text":"₱50,000–₱300,000+ per project once you can show results. Domain experts charge more than generalist engineers."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"The pattern: ","marks":[{"type":"bold"}]},{"type":"text","text":"the highest pay goes to people who finish things, verify the AI's work, and bring a field of their own."}]}]}]}]}$slide$::jsonb, 'Read one number slowly and let it land, then caveat cost of living before questions start. Expect the most questions here. Emphasize that domain expertise is a multiplier on every row.', 10
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

-- Slide 12: Your 90-day roadmap
INSERT INTO slides (deck_id, title, content, notes, sort_order)
SELECT id, 'Your 90-day roadmap', $slide${"type":"doc","content":[{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"This week: ","marks":[{"type":"bold"}]},{"type":"text","text":"use a free chatbot on one real task: a lecture outline, a rubric, a paper summary. Compare its answer with your own."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Days 1–30: ","marks":[{"type":"bold"}]},{"type":"text","text":"build a chatbot that answers from your own course notes using a no-code tool. Test it with ten real student questions."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Days 31–60: ","marks":[{"type":"bold"}]},{"type":"text","text":"pilot it with one class or one colleague. Write down what it got wrong and fix the material, not the AI."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Days 61–90: ","marks":[{"type":"bold"}]},{"type":"text","text":"pick one side-hustle path from earlier and make a first offer: a workshop, a study guide, a consulting conversation."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Closing thought: ","marks":[{"type":"bold"}]},{"type":"text","text":"you do not need to become an engineer. You need to become the expert in the room who also knows how to use the tools. Start this week."}]}]}]}]}$slide$::jsonb, 'Close with one concrete assignment: do the this-week item before Friday. Offer to take questions on side hustles and study paths first.', 11
FROM slide_decks WHERE slug = 'how-to-be-an-ai-engineer';

